reduce concurrency

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -83,12 +83,12 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo rm -rf /etc/apt/sources.list.d
-        sudo -E apt update -y
-        sudo -E apt purge -y azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
-        sudo -E apt autoremove -y --purge
-        sudo -E apt clean
-        sudo -E apt full-upgrade -y
-        sudo -E apt install -y --no-install-recommends ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
+        sudo -E apt-get update -y
+        # sudo -E apt-get purge -y azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
+        sudo -E apt-get autoremove -y --purge
+        sudo -E apt-get clean
+        sudo -E apt-get full-upgrade -y
+        sudo -E apt-get install -y --no-install-recommends ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
         bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
         g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
         libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 \
@@ -96,8 +96,8 @@ jobs:
         nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
         python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig \
         texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
-        sudo -E apt autoremove --purge
-        sudo -E apt clean
+        sudo -E apt-get autoremove --purge
+        sudo -E apt-get clean
         sudo timedatectl set-timezone "$TZ"
 
     - name: Clone source code
@@ -148,8 +148,8 @@ jobs:
       id: compile
       run: |
         cd openwrt
-        echo -e "$(nproc) thread compile"
-        make -j$(nproc) || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
+        # echo -e "$(nproc) thread compile"
+        make -j2 || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
         echo "STATUS=success" >> $GITHUB_ENV
 
     - name: Recompile the firmware
