concurrency

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -148,17 +148,17 @@ jobs:
       id: compile
       run: |
         cd openwrt
-        # echo -e "$(nproc) thread compile"
-        make -j1 V=s || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
+        echo -e "$(nproc) thread compile"
+        make -j$(nproc) || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
         echo "STATUS=success" >> $GITHUB_ENV
 
-    # - name: Recompile the firmware
-    #   id: recompile
-    #   if: env.STATUS != 'success'
-    #   run: |
-    #     cd openwrt
-    #     make -j1 V=s || exit 1
-    #     echo "STATUS=success" >> $GITHUB_ENV
+    - name: Retry compiling the firmware
+      id: retry
+      if: env.STATUS != 'success'
+      run: |
+        cd openwrt
+        make -j1 V=s || exit 1
+        echo "STATUS=success" >> $GITHUB_ENV
 
     - name: Set build variables
       if: env.STATUS == 'success'
