expand swap size

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -63,6 +63,12 @@ jobs:
       uses: easimon/maximize-build-space@v10
       with:
         root-reserve-mb: 4096
+        swap-size-mb: 10240
+        remove-dotnet: true
+        remove-android: true
+        remove-haskell: true
+        remove-codeql: true
+        remove-docker-images: true
 
     - name: Checkout
       uses: actions/checkout@main
@@ -71,8 +77,7 @@ jobs:
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-        docker rmi `docker images -q`
-        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
+        sudo rm -rf /etc/apt/sources.list.d
         sudo -E apt update -y
         sudo -E apt purge -y azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
         sudo -E apt autoremove -y --purge
@@ -121,7 +126,7 @@ jobs:
       if: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh_enabled }}
       with: 
         limit-access-to-actor: true
-        connect-timeout-seconds: 1800
+        # connect-timeout-seconds: 1800
 
     - name: Download package
       id: package
@@ -138,7 +143,7 @@ jobs:
       run: |
         cd openwrt
         # echo -e "$(nproc) thread compile"
-        make -j2 V=s || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
+        make -j1 || (echo "STATUS=failure" >> $GITHUB_ENV && exit 1)
         echo "STATUS=success" >> $GITHUB_ENV
 
     - name: Recompile the firmware
